### ISSUE TITLE
Consider changing some colors

### ISSUE THREAD

**Issue by lubien** [pawanpoudel/beginning-elm-code#1]
Thanks for your work on https://elmprogramming.com/ !

As of now the site has texts that are barely readable.

I originally came here to make a PR but I couldn't find a source code or repo so I'm making an issue here instead.

-----

![image](https://user-images.githubusercontent.com/9121359/65807179-98053200-e163-11e9-8fea-785b5a481ee5.png)
![image](https://user-images.githubusercontent.com/9121359/65807188-9e93a980-e163-11e9-9f78-2fd574f652f1.png)

-----

![image](https://user-images.githubusercontent.com/9121359/65807204-ab180200-e163-11e9-8354-e921a76c0d7c.png)
![image](https://user-images.githubusercontent.com/9121359/65807211-b3703d00-e163-11e9-9d9a-ab55ddfc9704.png)

**Comment by pawanpoudel** [comment]
Thank you so much for creating the issue and sorry for the late reply. I just returned from a long sabbatical. I have fixed the text color. Please let me know if you see anything else.
